<a href="https://colab.research.google.com/github/Aryan-Gupta2002/Deep-Learning---Tensorflow/blob/main/tensorflowFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Notebook for learning TensorFlow Fundamentals

Introduction To Tensors

In [2]:
# Importing Tensorflow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
# Creating a Vector
vector = tf.constant([10,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# Creating a Matrix
matrix = tf.constant([[10,5],[20,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [20,  8]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
anotherMatrix = tf.constant([[5.,3.],[5.,6.],[8.,4.]],dtype=tf.float16)
anotherMatrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 3.],
       [5., 6.],
       [8., 4.]], dtype=float16)>

In [10]:
anotherMatrix.ndim

2

In [11]:
# Creating our First tensor
tensor = tf.constant([[[10,3,2],[5,7,8]],
                      [[5,6,3],[8,5,6]],
                      [[9,5,7],[8,4,2]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  3,  2],
        [ 5,  7,  8]],

       [[ 5,  6,  3],
        [ 8,  5,  6]],

       [[ 9,  5,  7],
        [ 8,  4,  2]]], dtype=int32)>

In [12]:
tensor.ndim

3

•Scalar = A Single number(0-d tensor)  
•Vector = A number with direction (like in physics)(1-d tensor)  
•Matrix = a 2D array of numbers(2-d tensor)  
•Tensor = an n-D array of numbers(n can be any number)  

###Creating Tensors with 'tf.Variable'

In [13]:
# Creating a tensor with tf.variable() (changeable)
changeableTensor = tf.Variable([10,5])
unchangeableTensor = tf.constant([10,8])
changeableTensor, unchangeableTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [14]:
# Now to change a variable in 'tf.Variable'
# changeableTensor[0]=6 (this is not allowed)
# Use .assign() function
changeableTensor[0].assign(6)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([6, 5], dtype=int32)>

In [15]:
# Changing variable in constant is not allowed
# unchangeableTensor[0] = 7
# unchangeableTensor[0].assign(7)

### Creating Random Tensors  
Random Tensors are tensors of some arbitrary size (random) which conatains random numbers  

In [16]:
# Create two random (bt same) tensors
generator1 = tf.random.Generator.from_seed(42)
random1 = generator1.normal(shape=(2,2))
generator2 = tf.random.Generator.from_seed(42) # Same Seed
random2 = generator2.normal(shape=(2,2))
random3 = generator1.uniform(shape=(2,2)) #Uniformaly distributed, not same seed
random1,random2,random3, random1==random2 # same due to same seed

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.876197  , 0.49066722],
        [0.39786613, 0.5960511 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

### Shuffling the order of elements in our tensor

In [17]:
# Shuffling a tensor is very necessay as to avoid learning too much about the first kind of images (Overfittig)
notShuffled = tf.constant([[[3,7],[8,5],[7,9]],
                          [[4,7],[8,6],[2,1]],
                          [[7,2],[6,5],[4,3]]])
notShuffled.ndim
notShuffled

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[3, 7],
        [8, 5],
        [7, 9]],

       [[4, 7],
        [8, 6],
        [2, 1]],

       [[7, 2],
        [6, 5],
        [4, 3]]], dtype=int32)>

If you want the same order of shuffled tensors , use global + operation level seed

In [18]:
# tf.random.shuffle, shuffles only 1st dimension of a tensor
# Rows shuffles in our case
tf.random.set_seed(42)# Global level seed
tf.random.shuffle(notShuffled,seed=4)# Operational level seed

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[7, 2],
        [6, 5],
        [4, 3]],

       [[3, 7],
        [8, 5],
        [7, 9]],

       [[4, 7],
        [8, 6],
        [2, 1]]], dtype=int32)>

### Other ways of making tensors

In [19]:
#Create a tensor of all ones
tf1 = tf.ones([3,4])
tf2 = tf.ones([3,4],dtype=tf.int16)
tf1,tf2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=int16, numpy=
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=int16)>)

In [20]:
# Creating a tensor of all zeroes
t3 = tf.zeros(shape=(2,2))
t4 = tf.zeros([2,2],dtype=tf.int16)
t3,t4

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=int16, numpy=
 array([[0, 0],
        [0, 0]], dtype=int16)>)

###Turning Numpy arrays to Tensorflow Tensors
The main difference between numpy arrays and tensorflow tensors is that tensors can run on GPUs which is much faster.

In [21]:
import numpy as np
arr = np.arange(1,25,dtype=np.int32)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
# Converting to tensor
a = tf.constant(arr)
b = tf.constant(arr,shape=(4,3,2)) # Shape should be factor of the nomber of elements in np array
c = tf.constant(arr,shape=(6,4))
a,b,c

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16],
         [17, 18]],
 
        [[19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>)

### Getting Information from tensors
•Shape  
•Rank  
•Axis or Dimension  
•Size  

In [23]:
# Creating a tensor of rank 4 (4d tensor)
rank4tensor = tf.zeros(shape=(2,3,4,5)) # To visualize the shape of tensor, it is easier to imagine the shape from right (columns)
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank4tensor.shape,rank4tensor.ndim,tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
rank4tensor.shape[-1]
tf.size(rank4tensor)
tf.size(rank4tensor).numpy()

np.int32(120)

### Indexing Tensors

In [28]:
# Indexing tensoris same as python list
rank4tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
rank2tensor = tf.zeros(shape=(2,2))
rank2tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [34]:
#Adding an extra dimension in rank 2 dimension
rank3tensor = rank2tensor[...,tf.newaxis] # ... means include each axis before
#rank3tensor
#Alternative of newaxis
tf.expand_dims(rank2tensor, axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

# Basic Operations like add, substract, etc is just like in normal numpy

### ....

###One Hot Encoding

In [40]:
# Create a list of numbers
a = [2,3,4,5]
# One hot encodin the list
tf.one_hot(a,depth=4) # depth is necessary

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [42]:
# Customizing encoded values
tf.one_hot(a,depth=6,on_value='A',off_value='B')

<tf.Tensor: shape=(4, 6), dtype=string, numpy=
array([[b'B', b'B', b'A', b'B', b'B', b'B'],
       [b'B', b'B', b'B', b'A', b'B', b'B'],
       [b'B', b'B', b'B', b'B', b'A', b'B'],
       [b'B', b'B', b'B', b'B', b'B', b'A']], dtype=object)>

### Tensors and Numpy
Tensors and numpy are highly interactable with each other

In [43]:
J = tf.constant(np.array([3,7,8,10]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 3,  7,  8, 10])>

In [47]:
np.array(J),type(np.array(J)) #or
J.numpy(),type(J.numpy())

(array([ 3,  7,  8, 10]), numpy.ndarray)

### Finding access to GPU

In [3]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Sat Jan 24 12:34:44 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8             11W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----